# Generated by Django 3.0.6 on 2020-06-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0002_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to='Lessons/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesApp.Courses')),
            ],
        ),
    ]
