# Generated by Django 3.0.6 on 2020-06-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0004_auto_20200603_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lessons',
        ),
    ]
