# Generated by Django 3.0.6 on 2020-06-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0005_delete_lessons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='References',
        ),
    ]
