# Generated by Django 3.1.1 on 2020-10-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0006_delete_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cover',
            field=models.FileField(default=None, upload_to='Courses/'),
        ),
    ]
