# Generated by Django 3.1.1 on 2020-10-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0007_courses_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cover',
            field=models.FileField(upload_to='Courses/'),
        ),
    ]
