# Generated by Django 3.1.1 on 2021-03-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0009_auto_20210303_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='Courses/'),
        ),
    ]
