# Generated by Django 3.1.7 on 2021-03-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentsApp', '0002_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='semester',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
