# Generated by Django 3.1.7 on 2021-03-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentsApp', '0003_submissions_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='semester',
        ),
    ]
