# Generated by Django 3.1.7 on 2021-03-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20210305_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(choices=[('BSC.CS', 'Bsc computerScience'), ('MSC.CS', 'Msc computerScience')], default='BSC.CS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.CharField(choices=[('S1', 'semester 1'), ('S2', 'semester 2'), ('S3', 'semester 3'), ('S4', 'semester 4'), ('S5', 'semester 5'), ('S6', 'semester 6')], default='S1', max_length=3, null=True),
        ),
    ]
