# Generated by Django 3.1.7 on 2021-03-05 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursesApp', '0011_auto_20210303_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonname', models.CharField(max_length=100)),
                ('lesson', models.FileField(upload_to='Lessons/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesApp.courses')),
            ],
        ),
    ]
