# Generated by Django 3.1.1 on 2020-09-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lessonname',
            field=models.CharField(max_length=100),
        ),
    ]
